#!/bin/bash
# Do not use this in your script or project without asking for my permission.
# https://t.me/donottellmyname

# CPU BIG

# CPU freq max limit
FREQ=/sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq
BIG=/sys/devices/platform/exynos-migov/cl1/cl1_pm_qos_max_freq

chmod 644 $BIG

echo '2400000' > $BIG

if [ "$(cat $FREQ)" == "2496000" ]; then
echo '2496000' > $BIG
fi

chmod 444 $BIG

# CPU LITTLE

# CPU freq max limit
FREQ=/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
LITTLE=/sys/devices/platform/exynos-migov/cl0/cl0_pm_qos_max_freq

chmod 644 $LITTLE

echo '2002000' > $LITTLE

if [ "$(cat $FREQ)" == "2210000" ]; then
echo '2210000' > $LITTLE
fi

chmod 444 $LITTLE

# CPU Power efficient
chmod 644 /sys/module/workqueue/parameters/power_efficient
echo 'Y' > /sys/module/workqueue/parameters/power_efficient

# HMP
echo '524' > /sys/kernel/hmp/up_threshold
echo '312' > /sys/kernel/hmp/down_threshold

# GPU
GPU=/sys/kernel/gpu

chmod -R 644 $GPU

echo '897000' > $GPU/gpu_max_clock

if [ "$(cat $GPU/gpu_max_clock)" == "1209000" ]; then
echo '1209000' > $GPU/gpu_max_clock
echo '312000' > $GPU/gpu_min_clock
echo '1209000' > /sys/devices/platform/10300000.mali/highspeed_clock
else
echo '897000' > $GPU/gpu_max_clock
echo '312000' > $GPU/gpu_min_clock
echo '897000' > /sys/devices/platform/10300000.mali/highspeed_clock
fi

echo '75' > /sys/devices/platform/10300000.mali/highspeed_load
echo '0' > /sys/devices/platform/10300000.mali/tmu
echo 'coarse_demand' > /sys/devices/platform/10300000.mali/power_policy

# Extra
setprop debug.performance.tuning 0

echo -n "=========================>Ready<==========================";
sleep 2
labs
